"""
SQLAlchemy ORM Models for AIPMS Database
Defines all database tables: equipment, sensors, predictions, alerts, jobs
"""
from sqlalchemy import Column, String, Float, DateTime, Integer, Boolean, JSON, ForeignKey, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

Base = declarative_base()


class Equipment(Base):
    """Equipment unit (excavator, dumper, conveyor, etc.)"""
    __tablename__ = "equipment"
    
    id = Column(String(10), primary_key=True)  # e.g., EXC-01, DMP-03
    name = Column(String(100), nullable=False)
    type = Column(String(20), nullable=False)  # excavator, dumper, conveyor, drill
    location = Column(String(100), nullable=False)
    commissioned_date = Column(DateTime, nullable=True)
    total_operating_hours = Column(Float, default=0.0)
    status = Column(String(10), default='normal')  # normal, warning, critical, offline
    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    sensor_readings = relationship("SensorReading", back_populates="equipment")
    predictions = relationship("Prediction", back_populates="equipment")
    alerts = relationship("Alert", back_populates="equipment")
    maintenance_jobs = relationship("MaintenanceJob", back_populates="equipment")


class SensorReading(Base):
    """Raw sensor reading from equipment"""
    __tablename__ = "sensor_readings"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    equipment_id = Column(String(10), ForeignKey("equipment.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    sensor_name = Column(String(50), nullable=False)  # temperature, vibration, pressure, rpm, etc.
    value = Column(Float, nullable=False)
    unit = Column(String(20), nullable=False)  # °C, mm/s, bar, RPM, etc.
    data_quality_flag = Column(String(10), default='ok')  # ok, suspect, missing, stuck
    
    # Relationship
    equipment = relationship("Equipment", back_populates="sensor_readings")


class Prediction(Base):
    """ML model predictions for equipment"""
    __tablename__ = "predictions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    equipment_id = Column(String(10), ForeignKey("equipment.id"), nullable=False)
    timestamp = Column(DateTime, nullable=False, index=True)
    anomaly_score = Column(Float, nullable=False)  # 0-1
    anomaly_label = Column(String(10), nullable=False)  # normal, warning, critical
    failure_prob = Column(Float, nullable=False)  # 0-1: 7-day failure probability
    rul_hours = Column(Float, nullable=False)  # Remaining Useful Life in hours
    rul_confidence_low = Column(Float, nullable=True)  # 95% CI lower bound
    rul_confidence_high = Column(Float, nullable=True)  # 95% CI upper bound
    top_features_json = Column(JSON, nullable=True)  # [{sensor, shap_value, impact_pct}]
    model_version = Column(String(20), nullable=False)
    
    # Relationship
    equipment = relationship("Equipment", back_populates="predictions")


class Alert(Base):
    """Alert triggered by ML anomaly or failure prediction"""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    equipment_id = Column(String(10), ForeignKey("equipment.id"), nullable=False)
    triggered_at = Column(DateTime, nullable=False, index=True)
    severity = Column(String(10), nullable=False)  # warning, critical
    message = Column(Text, nullable=False)
    top_sensors = Column(JSON, nullable=True)  # Top 3 SHAP sensors
    failure_mode_hint = Column(String(100), nullable=True)  # FMEA mapping
    acknowledged = Column(Boolean, default=False)
    acknowledged_at = Column(DateTime, nullable=True)
    acknowledged_by = Column(String(50), nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    
    # Relationship
    equipment = relationship("Equipment", back_populates="alerts")


class MaintenanceJob(Base):
    """Scheduled maintenance job generated by optimizer"""
    __tablename__ = "maintenance_jobs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    equipment_id = Column(String(10), ForeignKey("equipment.id"), nullable=False)
    created_at = Column(DateTime, nullable=False)
    priority_score = Column(Float, nullable=False)  # 0-1
    priority_tier = Column(String(10), nullable=False)  # critical, warning, normal
    failure_prob = Column(Float, nullable=False)
    rul_hours = Column(Float, nullable=False)
    recommended_action = Column(Text, nullable=False)
    estimated_duration_hours = Column(Float, nullable=False)
    parts_required = Column(JSON, nullable=True)  # List of parts
    scheduled_window_start = Column(DateTime, nullable=True)
    scheduled_window_end = Column(DateTime, nullable=True)
    status = Column(String(20), default='scheduled')  # scheduled, in_progress, completed, deferred
    cmms_work_order_id = Column(String(50), nullable=True)
    notes = Column(Text, nullable=True)
    
    # Relationship
    equipment = relationship("Equipment", back_populates="maintenance_jobs")


class ModelMetadata(Base):
    """Track ML model versions and performance"""
    __tablename__ = "model_metadata"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    model_name = Column(String(50), unique=True, nullable=False)  # anomaly_detector, failure_predictor, rul_estimator
    version = Column(String(20), nullable=False)  # e.g., 1.0.0
    trained_at = Column(DateTime, nullable=False)
    dataset = Column(String(50), nullable=False)  # e.g., C-MAPSS FD001
    n_train_samples = Column(Integer, nullable=True)
    rmse = Column(Float, nullable=True)  # RUL estimator
    auc_roc = Column(Float, nullable=True)  # Failure predictor
    f1_score = Column(Float, nullable=True)  # Anomaly detector
    nasa_score = Column(Float, nullable=True)  # RUL asymmetric score
    feature_list_json = Column(JSON, nullable=True)
    hyperparams_json = Column(JSON, nullable=True)
    file_path = Column(String(200), nullable=False)
